GRANT SELECT, INSERT, UPDATE, DELETE ON PHIM TO ROLE_CONTENT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON VIDEO_PHAT TO ROLE_CONTENT_ADMIN;

GRANT SELECT ON THANH_VIEN TO ROLE_CC;
GRANT SELECT, UPDATE ON PHIEN_CHAT_AI TO ROLE_CC;