CREATE TABLE VAI_TRO (
    MaVT VARCHAR2(20) PRIMARY KEY,
    TenVT NVARCHAR2(50) NOT NULL,
    MoTa NVARCHAR2(500)
);

CREATE TABLE DOI_TAC (
    MaDT VARCHAR2(10) PRIMARY KEY,
    TenDT NVARCHAR2(100) NOT NULL,
    PhanLoai NVARCHAR2(50),
    Email VARCHAR2(100) NOT NULL UNIQUE,
    SoDienThoai VARCHAR2(15),
    ChietKhau NUMBER(5,2)
);

CREATE TABLE DIEN_VIEN (
    MaDV VARCHAR2(10) PRIMARY KEY,
    TenDV NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    QuocTich NVARCHAR2(50)
);

CREATE TABLE DAO_DIEN (
    MaDD VARCHAR2(10) PRIMARY KEY,
    TenDD NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    QuocTich NVARCHAR2(50)
);

CREATE TABLE TAG (
    MaTag VARCHAR2(10) PRIMARY KEY,
    TenTag NVARCHAR2(50) NOT NULL,
    MoTa NVARCHAR2(255)
);

CREATE TABLE DANH_MUC (
    MaDM VARCHAR2(10) PRIMARY KEY,
    TenDM NVARCHAR2(50) NOT NULL,
    MoTa NVARCHAR2(255)
);

CREATE TABLE TAI_KHOAN (
    MaTK VARCHAR2(10) PRIMARY KEY,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    MatKhau VARCHAR2(255) NOT NULL,
    TenHT NVARCHAR2(50),
    NgayDK DATE DEFAULT SYSDATE,
    TrangThai NVARCHAR2(20) DEFAULT 'Chưa xác thực',
    MaVT VARCHAR2(20),
    CONSTRAINT FK_TK_VT FOREIGN KEY (MaVT) REFERENCES VAI_TRO(MaVT)
);

CREATE TABLE THANH_VIEN (
    MaTK VARCHAR2(10) PRIMARY KEY,
    SoDienThoai VARCHAR2(15),
    NgaySinh DATE,
    GioiTinh NVARCHAR2(10),
    GoiHienTai NVARCHAR2(30) DEFAULT 'Miễn phí',
    CONSTRAINT FK_TV_TK FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
);

CREATE TABLE NHAN_VIEN (
    MaTK VARCHAR2(10) PRIMARY KEY,
    NgayBatDauLam DATE DEFAULT SYSDATE,
    TrangThaiLamViec NVARCHAR2(20) DEFAULT 'Đang làm việc',
    CONSTRAINT FK_NV_TK FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
);

CREATE TABLE KIEM_DUYET_VIEN (
    MaTK VARCHAR2(10) PRIMARY KEY,
    NhomPhuTrach NVARCHAR2(50),
    CONSTRAINT FK_KDV_NV FOREIGN KEY (MaTK) REFERENCES NHAN_VIEN(MaTK) ON DELETE CASCADE
);

CREATE TABLE QUAN_TRI_VIEN_NOI_DUNG (
    MaTK VARCHAR2(10) PRIMARY KEY,
    PhamViQuanLy NVARCHAR2(50),
    CONSTRAINT FK_QTVND_NV FOREIGN KEY (MaTK) REFERENCES NHAN_VIEN(MaTK) ON DELETE CASCADE
);

CREATE TABLE QUAN_TRI_VIEN_HE_THONG (
    MaTK VARCHAR2(10) PRIMARY KEY,
    DiaChiIPChoPhep VARCHAR2(50) NOT NULL,
    NgaySaoLuuCuoi TIMESTAMP,
    CONSTRAINT FK_QTVHT_NV FOREIGN KEY (MaTK) REFERENCES NHAN_VIEN(MaTK) ON DELETE CASCADE
);

CREATE TABLE CHAM_SOC_KHACH_HANG (
    MaTK VARCHAR2(10) PRIMARY KEY,
    TrangThai NVARCHAR2(20),
    SoPhienDangXuLy NUMBER(2) DEFAULT 0,
    CONSTRAINT FK_CSKH_NV FOREIGN KEY (MaTK) REFERENCES NHAN_VIEN(MaTK) ON DELETE CASCADE
);

CREATE TABLE NHAT_KY_HE_THONG (
    MaLog VARCHAR2(15) PRIMARY KEY,
    NgayGio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    HanhDong VARCHAR2(20),
    DoiTuong VARCHAR2(50),
    GhiChu NVARCHAR2(500),
    MaTK_NV VARCHAR2(10),
    CONSTRAINT FK_Log_NV FOREIGN KEY (MaTK_NV) REFERENCES NHAN_VIEN(MaTK) ON DELETE SET NULL
);

CREATE TABLE FAQ (
    MaFAQ VARCHAR2(10) PRIMARY KEY,
    CauHoi NVARCHAR2(500) NOT NULL,
    CauTraLoi NVARCHAR2(2000) NOT NULL,
    NhomChuDe NVARCHAR2(100),
    MaTK_QTVHT VARCHAR2(10),
    CONSTRAINT FK_FAQ_QTVHT FOREIGN KEY (MaTK_QTVHT) REFERENCES QUAN_TRI_VIEN_HE_THONG(MaTK) ON DELETE SET NULL
);

CREATE TABLE PHIM (
    MaPhim VARCHAR2(10) PRIMARY KEY,
    TenPhim NVARCHAR2(255) NOT NULL,
    Poster VARCHAR2(500),
    MoTa NVARCHAR2(2000),
    NamSX NUMBER(4),
    QuocGia NVARCHAR2(50),
    URLTrailer VARCHAR2(500),
    TrangThaiKD NVARCHAR2(20) DEFAULT 'Chờ duyệt',
    TrangThaiHT NVARCHAR2(20) DEFAULT 'Ẩn',
    LuotThich NUMBER(15) DEFAULT 0,
    MaDT VARCHAR2(10),
    MaTK_QTVND VARCHAR2(10),
    CONSTRAINT FK_Phim_DT FOREIGN KEY (MaDT) REFERENCES DOI_TAC(MaDT) ON DELETE SET NULL,
    CONSTRAINT FK_Phim_QTVND FOREIGN KEY (MaTK_QTVND) REFERENCES QUAN_TRI_VIEN_NOI_DUNG(MaTK) ON DELETE SET NULL
);

CREATE TABLE PHIM_LE (
    MaPhim VARCHAR2(10) PRIMARY KEY,
    DinhDang NVARCHAR2(50),
    CONSTRAINT FK_PhimLe_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE
);

CREATE TABLE PHIM_BO (
    MaPhim VARCHAR2(10) PRIMARY KEY,
    TongSoTap NUMBER(5),
    SoMua NUMBER(3),
    TrangThaiPS NVARCHAR2(30),
    LichPhatSong NVARCHAR2(255) DEFAULT 'Đang cập nhật' NOT NULL,
    CONSTRAINT FK_PhimBo_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE
);

CREATE TABLE PHIM_DIEN_VIEN (
    MaPhim VARCHAR2(10),
    MaDV VARCHAR2(10),
    VaiTro NVARCHAR2(50),
    PRIMARY KEY (MaPhim, MaDV),
    CONSTRAINT FK_PDV_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_PDV_DV FOREIGN KEY (MaDV) REFERENCES DIEN_VIEN(MaDV) ON DELETE CASCADE
);

CREATE TABLE PHIM_DAO_DIEN (
    MaPhim VARCHAR2(10),
    MaDD VARCHAR2(10),
    PRIMARY KEY (MaPhim, MaDD),
    CONSTRAINT FK_PDD_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_PDD_DD FOREIGN KEY (MaDD) REFERENCES DAO_DIEN(MaDD) ON DELETE CASCADE
);

CREATE TABLE PHIM_TAG (
    MaPhim VARCHAR2(10),
    MaTag VARCHAR2(10),
    PRIMARY KEY (MaPhim, MaTag),
    CONSTRAINT FK_PT_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_PT_Tag FOREIGN KEY (MaTag) REFERENCES TAG(MaTag) ON DELETE CASCADE
);

CREATE TABLE PHIM_DANH_MUC (
    MaPhim VARCHAR2(10),
    MaDM VARCHAR2(10),
    PRIMARY KEY (MaPhim, MaDM),
    CONSTRAINT FK_PDM_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_PDM_DM FOREIGN KEY (MaDM) REFERENCES DANH_MUC(MaDM) ON DELETE CASCADE
);

CREATE TABLE VIDEO_PHAT (
    MaVP VARCHAR2(10) PRIMARY KEY,
    YeuCauGoi NVARCHAR2(20),
    STT NUMBER(5),
    URLGoc VARCHAR2(500) NOT NULL,
    ThoiLuong NUMBER(10),
    MaPhim VARCHAR2(10),
    CONSTRAINT FK_VP_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE
);
CREATE TABLE PHIEN_BAN_VIDEO (
    MaPB VARCHAR2(10) PRIMARY KEY,
    YeuCauGoi NVARCHAR2(20),
    URLDoPhanGiai VARCHAR2(500) NOT NULL,
    DinhDangMaHoa VARCHAR2(20),
    MaVP VARCHAR2(10),
    CONSTRAINT FK_PBV_VP FOREIGN KEY (MaVP) REFERENCES VIDEO_PHAT(MaVP) ON DELETE CASCADE
);

CREATE TABLE HO_SO (
    MaHoSo VARCHAR2(10) PRIMARY KEY,
    TenHoSo NVARCHAR2(50) NOT NULL,
    AnhDaiDien VARCHAR2(255) DEFAULT 'DEFAULT',
    LoaiHoSo NVARCHAR2(20),
    MaPIN VARCHAR2(4),
    MaTK_TV VARCHAR2(10),
    CONSTRAINT FK_HS_TV FOREIGN KEY (MaTK_TV) REFERENCES THANH_VIEN(MaTK) ON DELETE CASCADE
);

CREATE TABLE LICH_SU_XEM (
    MaLSX VARCHAR2(10) PRIMARY KEY,
    TienDo NUMBER(10) DEFAULT 0,
    NgayTT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaHoSo VARCHAR2(10),
    MaVP VARCHAR2(10),
    CONSTRAINT FK_LSX_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE,
    CONSTRAINT FK_LSX_VP FOREIGN KEY (MaVP) REFERENCES VIDEO_PHAT(MaVP) ON DELETE CASCADE
);

CREATE TABLE THEM_DANH_SACH_CUA_TOI (
    MaHoSo VARCHAR2(10),
    MaPhim VARCHAR2(10),
    NgayThem DATE DEFAULT SYSDATE,
    PRIMARY KEY (MaHoSo, MaPhim),
    CONSTRAINT FK_YT_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE,
    CONSTRAINT FK_YT_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE
);

CREATE TABLE GOI_Y_PHIM (
    MaGY VARCHAR2(10) PRIMARY KEY,
    DiemSo NUMBER(5,2),
    NgayTao DATE DEFAULT SYSDATE,
    MaPhim VARCHAR2(10),
    MaHoSo VARCHAR2(10),
    CONSTRAINT FK_GY_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_GY_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE
);

CREATE TABLE THONG_BAO (
    MaTB VARCHAR2(10) PRIMARY KEY,
    TieuDe NVARCHAR2(255) NOT NULL,
    NoiDung NVARCHAR2(1000) NOT NULL,
    NgayGui TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaHoSo VARCHAR2(10),
    CONSTRAINT FK_TB_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE
);

CREATE TABLE BINH_LUAN_DANH_GIA (
    MaBL VARCHAR2(10) PRIMARY KEY,
    NoiDung NVARCHAR2(2000) NOT NULL,
    SoDiem NUMBER(3,2) NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai NVARCHAR2(20) DEFAULT 'Hiển thị',
    MaHoSo VARCHAR2(10),
    MaPhim VARCHAR2(10),
    CONSTRAINT FK_BL_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE,
    CONSTRAINT FK_BL_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE SET NULL
);


CREATE TABLE BAO_CAO_VI_PHAM (
    MaBC VARCHAR2(10),
    LyDo NVARCHAR2(2000) NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaBL VARCHAR2(10),
    MaHoSoGui VARCHAR2(10),
    CONSTRAINT PK_BAO_CAO_VI_PHAM PRIMARY KEY (MaBC),
    CONSTRAINT FK_BCVP_BINHLUAN FOREIGN KEY (MaBL) REFERENCES BINH_LUAN_DANH_GIA(MaBL) ON DELETE CASCADE,
    CONSTRAINT FK_BCVP_HOSO FOREIGN KEY (MaHoSoGui) REFERENCES HO_SO(MaHoSo)ON DELETE CASCADE
);
CREATE TABLE HE_THONG_DANH_DAU (
    MaHTDD VARCHAR2(10) PRIMARY KEY,
    DoTinCay NUMBER(5,2),
    NgayDanhDau DATE DEFAULT SYSDATE,
    LoaiDanhDau NVARCHAR2(50),
    GhiChu NVARCHAR2(500),
    MaBL VARCHAR2(10) NOT NULL UNIQUE,
    CONSTRAINT FK_HTDD_BINHLUAN FOREIGN KEY (MaBL) REFERENCES BINH_LUAN_DANH_GIA(MaBL) ON DELETE CASCADE
);

CREATE TABLE BINH_LUAN_KIEM_DUYET (
    MaBLKD VARCHAR2(10) PRIMARY KEY,
    NoiDung NVARCHAR2(2000),
    TrangThaiXL NVARCHAR2(20) DEFAULT 'Chờ xử lý',
    MaHTDD VARCHAR2(10),
    MaTK_KDV VARCHAR2(10),
    MaBC VARCHAR2(10),
    CONSTRAINT FK_BLK_KDV FOREIGN KEY (MaTK_KDV) REFERENCES KIEM_DUYET_VIEN(MaTK) ON DELETE SET NULL
);

CREATE TABLE PHIEN_CHAT_AI (
    MaPhien VARCHAR2(15) PRIMARY KEY,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai NVARCHAR2(20),
    MaHoSo VARCHAR2(10),
    MaTK_CSKH VARCHAR2(10),
    CONSTRAINT FK_PCAI_HS FOREIGN KEY (MaHoSo) REFERENCES HO_SO(MaHoSo) ON DELETE CASCADE,
    CONSTRAINT FK_PC_CSKH FOREIGN KEY (MaTK_CSKH) REFERENCES CHAM_SOC_KHACH_HANG(MaTK) ON DELETE SET NULL
);

CREATE TABLE TIN_NHAN_AI (
    MaTN VARCHAR2(15) PRIMARY KEY,
    NoiDung NVARCHAR2(2000) NOT NULL,
    NguoiGui VARCHAR2(10),
    ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaPhien VARCHAR2(15),
    CONSTRAINT FK_TNAI_Phien FOREIGN KEY (MaPhien) REFERENCES PHIEN_CHAT_AI(MaPhien) ON DELETE CASCADE
);

CREATE TABLE GOI_Y_KET_QUA (
    MaTN VARCHAR2(15),
    MaPhim VARCHAR2(10),
    PRIMARY KEY (MaTN, MaPhim),
    CONSTRAINT FK_GYKQ_TN FOREIGN KEY (MaTN) REFERENCES TIN_NHAN_AI(MaTN) ON DELETE CASCADE,
    CONSTRAINT FK_GYKQ_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE
);

CREATE TABLE GIAO_DICH (
    MaGD VARCHAR2(15) PRIMARY KEY,
    SoTien NUMBER(15,0),
    TrangThai NVARCHAR2(20) DEFAULT 'Đang xử lý',
    NgayGiaoDich DATE DEFAULT SYSDATE,
    MaTK_TV VARCHAR2(10),
    MaDT VARCHAR2(10),
    CONSTRAINT FK_GD_TV FOREIGN KEY (MaTK_TV) REFERENCES THANH_VIEN(MaTK) ON DELETE SET NULL,
    CONSTRAINT FK_GD_DT FOREIGN KEY (MaDT) REFERENCES DOI_TAC(MaDT) ON DELETE SET NULL
);

CREATE TABLE QUANG_CAO (
    MaQC VARCHAR2(10) PRIMARY KEY,
    SoLuotYeuCau NUMBER(10),
    SoLuotXem NUMBER(10),
    DonGia NUMBER(10,2),
    TrangThai NVARCHAR2(20) DEFAULT 'Chờ duyệt',
    URLVideo VARCHAR2(500),
    MaDT VARCHAR2(10),
    CONSTRAINT FK_QC_DT FOREIGN KEY (MaDT) REFERENCES DOI_TAC(MaDT) ON DELETE CASCADE
);

CREATE TABLE PHIM_QUANG_CAO (
    MaPhim VARCHAR2(10),
    MaQC VARCHAR2(10),
    ThoiDiemPhat NUMBER(10),
    PRIMARY KEY (MaPhim, MaQC),
    CONSTRAINT FK_PQC_Phim FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim) ON DELETE CASCADE,
    CONSTRAINT FK_PQC_QC FOREIGN KEY (MaQC) REFERENCES QUANG_CAO(MaQC) ON DELETE CASCADE
);
--TRIGGER
CREATE OR REPLACE TRIGGER TRG_DIEN_VIEN
BEFORE INSERT OR UPDATE ON DIEN_VIEN
FOR EACH ROW
BEGIN
    IF :NEW.NgaySinh IS NOT NULL AND :NEW.NgaySinh > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ngay sinh dien vien khong duoc lon hon ngay hien tai.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DAO_DIEN
BEFORE INSERT OR UPDATE ON DAO_DIEN
FOR EACH ROW
BEGIN
    IF :NEW.NgaySinh IS NOT NULL AND :NEW.NgaySinh > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Ngay sinh dao dien khong duoc lon hon ngay hien tai.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_THANH_VIEN
BEFORE INSERT OR UPDATE ON THANH_VIEN
FOR EACH ROW
BEGIN
    IF :NEW.NgaySinh IS NOT NULL AND :NEW.NgaySinh > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20003, 'Ngay sinh thanh vien khong duoc lon hon ngay hien tai.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_NHAN_VIEN
BEFORE INSERT OR UPDATE ON NHAN_VIEN
FOR EACH ROW
BEGIN
    IF :NEW.NgayBatDauLam IS NOT NULL AND :NEW.NgayBatDauLam > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20004, 'Ngay vao lam khong duoc lon hon ngay hien tai.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_HE_THONG_DANH_DAU
BEFORE INSERT OR UPDATE ON HE_THONG_DANH_DAU
FOR EACH ROW
BEGIN
    IF :NEW.NgayDanhDau IS NOT NULL AND :NEW.NgayDanhDau > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20005, 'Ngay danh dau khong duoc lon hon ngay hien tai.');
    END IF;
END;
/

-- AFTER TABLE
-- 1. Bảng VAI_TRO
ALTER TABLE VAI_TRO ADD CONSTRAINT CHK_MaVT CHECK (MaVT IN ('USER', 'MOD', 'CONTENT_ADMIN', 'SYS_ADMIN', 'CC'));

-- 2. Bảng DOI_TAC
ALTER TABLE DOI_TAC ADD CONSTRAINT CHK_SDT_DOITAC CHECK (REGEXP_LIKE(SoDienThoai, '^\+?[0-9]{8,15}$'));
ALTER TABLE DOI_TAC ADD CONSTRAINT CHK_PhanLoaiDT CHECK (PhanLoai IN ('Cổng thanh toán', 'Nhà cung cấp nội dung', 'Quảng cáo'));
ALTER TABLE DOI_TAC ADD CONSTRAINT CHK_ChietKhau CHECK (ChietKhau BETWEEN 0 AND 100);
ALTER TABLE DOI_TAC ADD CONSTRAINT CHK_Email_DT CHECK (Email LIKE '%@%.%');

-- 3. Bảng TAI_KHOAN
ALTER TABLE TAI_KHOAN ADD CONSTRAINT CHK_Email_Format CHECK (Email LIKE '%@%.%');
ALTER TABLE TAI_KHOAN ADD CONSTRAINT CHK_TrangThai_TK CHECK (TrangThai IN ('Hoạt động', 'Bị khóa', 'Chưa xác thực'));

-- 4. Bảng THANH_VIEN
ALTER TABLE THANH_VIEN ADD CONSTRAINT CHK_SDT CHECK (REGEXP_LIKE(SoDienThoai, '^0[0-9]{9}$'));
ALTER TABLE THANH_VIEN ADD CONSTRAINT CHK_GioiTinh CHECK (GioiTinh IN ('Nam', 'Nữ', 'Khác'));
ALTER TABLE THANH_VIEN ADD CONSTRAINT CHK_GoiDichVu CHECK (GoiHienTai IN ('Miễn phí', 'VIP'));

-- 5. Bảng NHAN_VIEN
ALTER TABLE NHAN_VIEN ADD CONSTRAINT CHK_TT_LamViec CHECK (TrangThaiLamViec IN ('Đang làm việc', 'Nghỉ phép', 'Đã nghỉ việc'));

-- 6. Bảng KIEM_DUYET_VIEN
ALTER TABLE KIEM_DUYET_VIEN ADD CONSTRAINT CHK_NhomPhuTrach CHECK (NhomPhuTrach IN ('toxic', 'sensitive', 'quality'));

-- 7. Bảng QUAN_TRI_VIEN_NOI_DUNG
ALTER TABLE QUAN_TRI_VIEN_NOI_DUNG ADD CONSTRAINT CHK_PhamVi CHECK (PhamViQuanLy IN ('Phim điện ảnh', 'Phim truyền hình', 'Phim hoạt hình', 'Phim tài liệu'));

-- 8. Bảng QUAN_TRI_VIEN_HE_THONG
ALTER TABLE QUAN_TRI_VIEN_HE_THONG ADD CONSTRAINT CHK_IPv4 CHECK (REGEXP_LIKE(DiaChiIPChoPhep, '^([0-9]{1,3}\.){3}[0-9]{1,3}$'));

-- 9. Bảng CHAM_SOC_KHACH_HANG
ALTER TABLE CHAM_SOC_KHACH_HANG ADD CONSTRAINT CHK_TrangThai_CSKH CHECK (TrangThai IN ('Sẵn sàng', 'Đang bận'));

-- 10. Bảng NHAT_KY_HE_THONG
ALTER TABLE NHAT_KY_HE_THONG ADD CONSTRAINT CHK_HanhDong CHECK (HanhDong IN ('LOGIN','INSERT', 'CREATE', 'UPDATE', 'DELETE'));

-- 11. Bảng FAQ
ALTER TABLE FAQ ADD CONSTRAINT CHK_NhomFAQ CHECK (NhomChuDe IN ('Gói cước', 'Lỗi ứng dụng', 'Ứng dụng', 'Tài khoản', 'Bảo mật', 'Khác'));

-- 12. Bảng PHIM
ALTER TABLE PHIM ADD CONSTRAINT CHK_NamSX CHECK (NamSX BETWEEN 1888 AND 2031);
ALTER TABLE PHIM ADD CONSTRAINT CHK_TT_KD CHECK (TrangThaiKD IN ('Chờ duyệt', 'Đã duyệt', 'Từ chối'));
ALTER TABLE PHIM ADD CONSTRAINT CHK_TT_HT CHECK (TrangThaiHT IN ('Công khai', 'Ẩn', 'Sắp chiếu'));
ALTER TABLE PHIM ADD CONSTRAINT CHK_LuotThich CHECK (LuotThich >= 0);

-- 13. Bảng PHIM_LE
ALTER TABLE PHIM_LE ADD CONSTRAINT CHK_DinhDangLe CHECK (DinhDang IN ('2D', '3D'));

-- 14. Bảng PHIM_BO
ALTER TABLE PHIM_BO ADD CONSTRAINT CHK_TongSoTap CHECK (TongSoTap > 0);
ALTER TABLE PHIM_BO ADD CONSTRAINT CHK_SoMua CHECK (SoMua > 0);
ALTER TABLE PHIM_BO ADD CONSTRAINT CHK_TT_PhatSong CHECK (TrangThaiPS IN ('Đang chiếu', 'Hoàn tất phát sóng'));

-- 15. Bảng PHIM_DIEN_VIEN
ALTER TABLE PHIM_DIEN_VIEN ADD CONSTRAINT CHK_VaiTroDV CHECK (VaiTro IN ('Nam chính', 'Nữ chính', 'Nam phụ', 'Nữ phụ', 'Khách mời'));

-- 16. Bảng VIDEO_PHAT
ALTER TABLE VIDEO_PHAT ADD CONSTRAINT CHK_GoiVideo CHECK (YeuCauGoi IN ('Miễn phí', 'VIP'));
ALTER TABLE VIDEO_PHAT ADD CONSTRAINT CHK_STT_Video CHECK (STT > 0);
ALTER TABLE VIDEO_PHAT ADD CONSTRAINT CHK_ThoiLuong CHECK (ThoiLuong > 0);

-- 17. Bảng PHIEN_BAN_VIDEO
ALTER TABLE PHIEN_BAN_VIDEO ADD CONSTRAINT CHK_GoiPB CHECK (YeuCauGoi IN ('Miễn phí', 'VIP'));
ALTER TABLE PHIEN_BAN_VIDEO ADD CONSTRAINT CHK_MaHoa CHECK (DinhDangMaHoa IN ('H.264', 'H.265', 'VP9', 'AV1'));

-- 18. Bảng HO_SO
ALTER TABLE HO_SO ADD CONSTRAINT CHK_LoaiHoSo CHECK (LoaiHoSo IN ('Trẻ em', 'Người lớn'));
ALTER TABLE HO_SO ADD CONSTRAINT CHK_MaPIN CHECK (REGEXP_LIKE(MaPIN, '^[0-9]{4}$'));

-- 19. Bảng LICH_SU_XEM
ALTER TABLE LICH_SU_XEM ADD CONSTRAINT CHK_TienDo CHECK (TienDo >= 0);

-- 20. Bảng GOI_Y_PHIM
ALTER TABLE GOI_Y_PHIM ADD CONSTRAINT CHK_DiemSo CHECK (DiemSo BETWEEN 0 AND 100);

-- 21. Bảng BINH_LUAN_DANH_GIA
ALTER TABLE BINH_LUAN_DANH_GIA ADD CONSTRAINT CHK_Diem CHECK (SoDiem BETWEEN 1 AND 5);
ALTER TABLE BINH_LUAN_DANH_GIA ADD CONSTRAINT CHK_TT_BL CHECK (TrangThai IN ('Hiển thị', 'Bị ẩn hệ thống'));

-- 22. Bảng HE_THONG_DANH_DAU
ALTER TABLE HE_THONG_DANH_DAU ADD CONSTRAINT CHK_DoTinCay CHECK (DoTinCay BETWEEN 0 AND 100);
ALTER TABLE HE_THONG_DANH_DAU ADD CONSTRAINT CHK_LoaiDanhDau CHECK (LoaiDanhDau IN ('spam', 'hate_speech', 'harrassment', 'nsfw', 'violence', 'self_harm', 'fake_info', 'copyright', 'off_topic'));

-- 23. Bảng BINH_LUAN_KIEM_DUYET
ALTER TABLE BINH_LUAN_KIEM_DUYET ADD CONSTRAINT CHK_TT_BLK CHECK (TrangThaiXL IN ('Chờ xử lý', 'Đã ẩn', 'Bác bỏ'));

-- 24. Bảng PHIEN_CHAT_AI
ALTER TABLE PHIEN_CHAT_AI ADD CONSTRAINT CHK_TrangThai_PCAI CHECK (TrangThai IN ('Đang chat', 'Kết thúc', 'Chuyển nhân viên'));

-- 25. Bảng TIN_NHAN_AI
ALTER TABLE TIN_NHAN_AI ADD CONSTRAINT CHK_NguoiGui_TNAI CHECK (NguoiGui IN ('USER', 'AI', 'CC'));

-- 26. Bảng GIAO_DICH
ALTER TABLE GIAO_DICH ADD CONSTRAINT CHK_SoTien CHECK (SoTien > 0);
ALTER TABLE GIAO_DICH ADD CONSTRAINT CHK_TT_GD CHECK (TrangThai IN ('Thành công', 'Thất bại', 'Đang xử lý'));

-- 27. Bảng QUANG_CAO
ALTER TABLE QUANG_CAO ADD CONSTRAINT CHK_YeuCauView CHECK (SoLuotYeuCau > 0);
ALTER TABLE QUANG_CAO ADD CONSTRAINT CHK_ThucTeView CHECK (SoLuotXem >= 0);
ALTER TABLE QUANG_CAO ADD CONSTRAINT CHK_DonGiaQC CHECK (DonGia > 0);
ALTER TABLE QUANG_CAO ADD CONSTRAINT CHK_TrangThai_QC CHECK (TrangThai IN ('Hoạt động', 'Tạm dừng', 'Chờ duyệt', 'Kết thúc'));

-- 28. Bảng PHIM_QUANG_CAO
ALTER TABLE PHIM_QUANG_CAO ADD CONSTRAINT CHK_ThoiDiem CHECK (ThoiDiemPhat >= 0);

