
-- KHỞI TẠO CÁC ROLE 

CREATE ROLE ROLE_USER;
CREATE ROLE ROLE_CC;
CREATE ROLE ROLE_MOD;
CREATE ROLE ROLE_CONTENT_ADMIN;

-- PHẦN 2: KHỞI TẠO TÀI KHOẢN NGƯỜI DÙNG VÀ GÁN VÀO ROLE

CREATE USER usr_sysadmin IDENTIFIED BY "Admin@123" PROFILE ADMIN_PROFILE;
CREATE USER usr_content IDENTIFIED BY "Content@123" PROFILE ADMIN_PROFILE;
CREATE USER usr_mod IDENTIFIED BY "Mod@123" PROFILE ADMIN_PROFILE;
CREATE USER usr_member IDENTIFIED BY "Member@123" PROFILE ADMIN_PROFILE;
CREATE USER usr_cskh IDENTIFIED BY "Cskh@123" PROFILE ADMIN_PROFILE;

GRANT CREATE SESSION TO usr_sysadmin, usr_content, usr_mod, usr_member, usr_cskh;

GRANT DBA TO usr_sysadmin;
GRANT ROLE_CONTENT_ADMIN TO usr_content;
GRANT ROLE_MOD TO usr_mod;
GRANT ROLE_USER TO usr_member;
GRANT ROLE_CC TO usr_cskh;

ALTER USER usr_content DEFAULT ROLE ROLE_CONTENT_ADMIN;
ALTER USER usr_mod DEFAULT ROLE ROLE_MOD;
ALTER USER usr_cskh DEFAULT ROLE ROLE_CC;
ALTER USER usr_member DEFAULT ROLE ROLE_USER;