

CREATE MATERIALIZED VIEW LOG ON PHIM
WITH ROWID, SEQUENCE (MaPhim, TenPhim, LuotThich)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON VIDEO_PHAT
WITH ROWID, SEQUENCE (MaVP, MaPhim)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON LICH_SU_XEM
WITH ROWID, SEQUENCE (MaLSX, MaVP)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON BINH_LUAN_DANH_GIA
WITH ROWID, SEQUENCE (MaBL, MaPhim)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW MV_PHIM_THINH_HANH
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT P.MaPhim, P.TenPhim, COUNT(DISTINCT LSX.MaLSX) AS LuotXem, P.LuotThich,
    COUNT(DISTINCT BL.MaBL) AS TongSoBinhLuan,
    (
        COUNT(DISTINCT LSX.MaLSX)
        + P.LuotThich
        + COUNT(DISTINCT BL.MaBL)
    ) AS SoLuotTuongTac
FROM PHIM P
LEFT JOIN VIDEO_PHAT VP ON P.MaPhim = VP.MaPhim
LEFT JOIN LICH_SU_XEM LSX ON VP.MaVP = LSX.MaVP
LEFT JOIN BINH_LUAN_DANH_GIA BL ON P.MaPhim = BL.MaPhim
GROUP BY P.MaPhim, P.TenPhim, P.LuotThich;

CREATE OR REPLACE VIEW V_TOP10_PHIM_THINH_HANH AS
SELECT MaPhim, TenPhim, LuotXem, LuotThich, TongSoBinhLuan, SoLuotTuongTac
FROM MV_PHIM_THINH_HANH
ORDER BY SoLuotTuongTac DESC
FETCH FIRST 10 ROWS ONLY;


--*LỊCH SỬ XEM*
CREATE INDEX IDX_LSX_MAHOSO_NGAY 
ON LICH_SU_XEM(MaHoSo, NgayTT DESC);

CREATE OR REPLACE VIEW V_LICH_SU_XEM_PHIM AS
SELECT LS.MaHoSo, P.MaPhim, P.TenPhim, P.Poster, 
    CASE 
        WHEN VP.STT IS NULL THEN NULL
        ELSE VP.STT 
    END AS TapPhim, VP.ThoiLuong AS TongThoiLuong,  LS.TienDo AS ThoiGianDaXem, LS.NgayTT AS NgayXemGanNhat,
    CASE 
        WHEN VP.ThoiLuong > 0 
        THEN ROUND((LS.TienDo / VP.ThoiLuong) * 100, 2)
        ELSE 0 
    END AS PhanTramDaXem
FROM LICH_SU_XEM LS
    JOIN VIDEO_PHAT VP ON LS.MaVP = VP.MaVP
    JOIN PHIM P ON VP.MaPhim = P.MaPhim;



--*TỔNG DOANH THU HỆ THỐNG*
CREATE INDEX IDX_GIAO_DICH_TRANGTHAI
ON GIAO_DICH(TrangThai);

CREATE INDEX IDX_QUANG_CAO_TRANGTHAI
ON QUANG_CAO(TrangThai);

CREATE OR REPLACE VIEW VIEW_DOANH_THU AS 
SELECT 
    NVL(
        (
            SELECT SUM(SoTien)
            FROM GIAO_DICH
            WHERE TrangThai = 'Thành công'
        ), 0
    ) AS Doanh_thu_giao_dich,
    NVL(
        (
            SELECT SUM(SoLuotXem * DonGia)
            FROM QUANG_CAO
            WHERE TrangThai = 'Đã duyệt'
        ), 0
    ) AS Doanh_thu_quang_cao, 
    NVL(
        (
            SELECT SUM(SoTien)
            FROM GIAO_DICH
            WHERE TrangThai = 'Thành công'
        ), 0
    ) +
    NVL(
        (
            SELECT SUM(SoLuotXem * DonGia)
            FROM QUANG_CAO
            WHERE TrangThai = 'Đã duyệt'
        ), 0
    ) AS TongDoanhThu
FROM DUAL;

--*DANH SÁCH BÌNH LUẬN VI PHẠM*
CREATE INDEX IDX_BL
ON BINH_LUAN_DANH_GIA(TRANGTHAI);

CREATE OR REPLACE VIEW VIEW_BINH_LUAN_VI_PHAM AS
SELECT MaBL, NoiDung, NgayTao, TRANGTHAI, MAHOSO
FROM BINH_LUAN_DANH_GIA
WHERE TRANGTHAI=N'Bị ẩn hệ thống';



--*Thống kê quảng cáo*
CREATE OR REPLACE VIEW VIEW_QUANG_CAO_DO AS
SELECT MADT, MAQC, SOLUOTYEUCAU, SOLUOTXEM, DONGIA, SOLUOTXEM*DONGIA AS DOANHTHU 
FROM QUANG_CAO
WHERE TRANGTHAI=N'Hoạt động';




--*Danh sách người dùng VIP*
CREATE INDEX IDX_THANH_VIEN
ON THANH_VIEN(GOIHIENTAI);

CREATE OR REPLACE VIEW VIEW_THANH_VIEN_VIP AS
SELECT *
FROM THANH_VIEN
WHERE GOIHIENTAI=N'VIP';


--*Thống kê lượt xem theo danh mục*
CREATE OR REPLACE VIEW VIEW_LUOT_XEM_DANH_MUC AS
SELECT DM.MaDM, DM.TenDM, COUNT(DISTINCT LSX.MaLSX) AS LuotXemDanhMuc
FROM DANH_MUC DM
    LEFT JOIN PHIM_DANH_MUC PDM ON DM.MaDM = PDM.MaDM
    LEFT JOIN PHIM P ON P.MaPhim = PDM.MaPhim
    LEFT JOIN VIDEO_PHAT VP ON VP.MaPhim = P.MaPhim
    LEFT JOIN LICH_SU_XEM LSX ON LSX.MaVP = VP.MaVP
GROUP BY DM.MaDM, DM.TenDM;
